services:
  - type: web
    name: puremail
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python -c "from app import app; from extensions import db; with app.app_context(): db.create_all()"
    startCommand: |
      export PYTHONPATH=/opt/render/project/src:$PYTHONPATH
      gunicorn --preload --workers 4 --threads 2 --timeout 180 --max-requests 1000 --max-requests-jitter 50 'app:app'
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DATABASE_URL
        fromDatabase:
          name: puremail-db
          property: connectionString
      - key: FLASK_APP
        value: app.py
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: UPLOAD_FOLDER
        value: /opt/render/project/src/uploads
      - key: MAX_CONTENT_LENGTH
        value: 10485760
      - key: SQLALCHEMY_TRACK_MODIFICATIONS
        value: "False"
      - key: SSL_MODE
        value: require
      - key: POSTGRES_SSLMODE
        value: require
      - key: PYTHONPATH
        value: /opt/render/project/src
    healthCheckPath: /
    autoDeploy: false
    disk:
      name: uploads
      mountPath: /opt/render/project/src/uploads
      sizeGB: 1

databases:
  - name: puremail-db
    plan: starter
    ipAllowList: []
