services:
  - type: web
    name: puremail
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --timeout 120 --workers 4 --threads 2
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DATABASE_URL
        fromDatabase:
          name: puremail-db
          property: connectionString
      - key: FLASK_APP
        value: app.py
      - key: FLASK_ENV
        value: production
      - key: UPLOAD_FOLDER
        value: /opt/render/project/src/uploads
      - key: MAX_CONTENT_LENGTH
        value: 10485760
      - key: SQLALCHEMY_TRACK_MODIFICATIONS
        value: "False"
      - key: SSL_MODE
        value: require
      - key: POSTGRES_SSLMODE
        value: require
    healthCheckPath: /
    autoDeploy: false

databases:
  - name: puremail-db
    plan: free
    ipAllowList: []
