services:
  - type: web
    name: puremail
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python -c "
      from app import app, db;
      from models import *;
      with app.app_context():
          db.create_all();
          try:
              db.session.execute('ALTER TABLE verifications ADD COLUMN IF NOT EXISTS created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP');
              db.session.execute('ALTER TABLE verifications ADD COLUMN IF NOT EXISTS status VARCHAR(20) DEFAULT \'pending\'');
              db.session.execute('ALTER TABLE appsumo_codes ADD COLUMN IF NOT EXISTS is_redeemed BOOLEAN DEFAULT FALSE');
              db.session.commit()
          except:
              db.session.rollback()
      "
    startCommand: |
      export PYTHONPATH=/opt/render/project/src:$PYTHONPATH
      gunicorn --preload --workers 4 --threads 2 --timeout 180 --max-requests 1000 --max-requests-jitter 50 'app:app'
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DATABASE_URL
        fromDatabase:
          name: puremail-db
          property: connectionString
      - key: FLASK_APP
        value: app.py
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: UPLOAD_FOLDER
        value: /opt/render/project/src/uploads
      - key: MAX_CONTENT_LENGTH
        value: 10485760
      - key: SQLALCHEMY_TRACK_MODIFICATIONS
        value: "False"
      - key: POSTGRES_SSLMODE
        value: require
      - key: POSTGRES_CONNECT_TIMEOUT
        value: "30"
      - key: POSTGRES_KEEPALIVES
        value: "1"
      - key: POSTGRES_KEEPALIVES_IDLE
        value: "30"
      - key: POSTGRES_KEEPALIVES_INTERVAL
        value: "10"
      - key: POSTGRES_KEEPALIVES_COUNT
        value: "5"
      - key: PYTHONPATH
        value: /opt/render/project/src
    healthCheckPath: /
    autoDeploy: false
    disk:
      name: uploads
      mountPath: /opt/render/project/src/uploads
      sizeGB: 1

databases:
  - name: puremail-db
    plan: starter
    ipAllowList: []
    postgresMajorVersion: 15
