services:
  - type: web
    name: puremail
    env: python
    buildCommand: |
      pip install -r requirements.txt
    startCommand: |
      python init_db.py
      gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DATABASE_URL
        fromDatabase:
          name: puremail-db
          property: connectionString
      - key: UPLOAD_FOLDER
        value: /opt/render/project/src/uploads
      - key: MAX_CONTENT_LENGTH
        value: 10485760

databases:
  - name: puremail-db
    databaseName: puremail
    user: puremail
    plan: free
    ipAllowList: [] # Allow all IPs
