services:
  - type: web
    name: puremail
    env: python
    buildCommand: |
      pip install -r requirements.txt
    startCommand: |
      python init_db.py
      gunicorn -c gunicorn.conf.py app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.18
      - key: FLASK_APP
        value: app.py
      - key: FLASK_ENV
        value: production
      - key: PORT
        value: 10000
      - key: WORKERS
        value: 4
      - key: TIMEOUT
        value: 120
      - key: UPLOAD_FOLDER
        value: /opt/render/project/src/uploads
      - key: MAX_CONTENT_LENGTH
        value: 10485760
      - key: PERMANENT_SESSION_LIFETIME
        value: 3600
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: puremail-db
          property: connectionString

databases:
  - name: puremail-db
    databaseName: puremail
    user: puremail
